AgregatorLinkow/Models/Link.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AgregatorLinkow.Models
{
    public class Link
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Column(TypeName = "varchar(40)")]
        [MaxLength(40)]
        public string Name { get; set; }
        [Column(TypeName = "varchar(250)")]
        [MaxLength(250)]
        public string Description {get; set;}
        [Required]
        [Column(TypeName = "varchar(250)")]
        [MaxLength(250)]
        public string Url { get; set; }
        public DateTime DateAdded { get; set; } //Data dodania linku
        [Column(TypeName = "varchar(250)")]
        public string UserId { get; set; } //Id użytkownika, przez którego został dodany link
        [Required]
        public int Likes { get; set; } //Liczba polubień
    }
}

AgregatorLinkow/Controllers/LinksController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AgregatorLinkow.Models;
using Microsoft.AspNetCore.Identity;
using System.Diagnostics;

namespace AgregatorLinkow.Controllers
{
    public class LinksController : Controller
    {
        private readonly LinkContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public LinksController(LinkContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? pageNumber) //Strona główna
        {
            var links = from l in _context.Links select l;
            links = links.Where(l => DateTime.Compare(l.DateAdded, DateTime.Now.AddDays(-5)) >= 0); //Warunek dot. daty - wyświetlania max. 5 dni od dodania
            links = links.OrderByDescending(l => l.Likes); //Sortowanie według ilości polubień

            return View(await PaginatedList<Link>.CreateAsync(links.AsNoTracking(), pageNumber ?? 1, 100));
        }

        [HttpGet]
        public async Task<IActionResult> UserLinks(int? pageNumber) //Wszystkie linki dodane przez zalogowanego użytkownika
        {
            var loggedUserId = _userManager.GetUserId(HttpContext.User);
            var links = from l in _context.Links select l;
            links = links.Where(l => l.UserId == loggedUserId);
            links = links.OrderByDescending(l => l.Likes);

            return View(await PaginatedList<Link>.CreateAsync(links.AsNoTracking(), pageNumber ?? 1, 100));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new Link());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Url")] Link link)
        {
            ViewBag.Message = ModelState.IsValid;
            if (ModelState.IsValid)
            {
                link.DateAdded = DateTime.Now;
                link.UserId = _userManager.GetUserId(HttpContext.User);
                link.Likes = 0;
                _context.Links.Add(link);
                await _context.SaveChangesAsync();
            }
            return View(link);
        }

        [HttpPost]
        public async Task<JsonResult> Like(int id)
        {
            var link = await _context.Links.FindAsync(id);
            var loggedUserId = _userManager.GetUserId(HttpContext.User);

            if (link != null)
            {
                link.Likes++;
                _context.Links.Update(link);
                AddNewLike(loggedUserId, id);

                await _context.SaveChangesAsync();
                return Json(true);
            }
            return Json(false);
        }

        private void AddNewLike(string userId, int linkId)
        {
            Like like = new Like();
            like.UserId = userId;
            like.LinkId = linkId;
            _context.Likes.Add(like);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgregatorLinkow/Views/Links/Create.cshtml
@model AgregatorLinkow.Models.Link

@{
    ViewData["Title"] = "Create";
}

<h1 style="margin-bottom: 20pt">Add new link</h1>
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" style="width: 40%"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea class="form-control" asp-for="Description" rows="3" style="width: 40%"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" style="width: 40%"/>
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button class="btn btn-dark">Add</button>
            </div>
    </form>

@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        window.onload = function () {
            $("#LinkModal").modal("show");
        };
    </script>
}

<div style="margin-top: 20pt">
    <a asp-controller="Links" asp-action="UserLinks">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<!--Komunikat:-->
<div class="modal fade" id="LinkModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                New link added successfully.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>

AgregatorLinkow/Views/Links/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> _signInManager;
@inject UserManager<IdentityUser> _userManager;
@inject LinkContext _context;
@model PaginatedList<AgregatorLinkow.Models.Link>;


@{
    ViewData["Title"] = "Index";
    var likeInputDisabled = "";
    var likeInputValue = "Like";
}

<h1 class="text-center" style="margin-bottom: 20pt">List of links</h1>

<ol start="@(1 + (Model.PageIndex - 1) * 100)">
    @foreach (var item in Model)
    {
        <li>
            <div>
                <span style="margin-right: 10pt">@Html.DisplayFor(modelItem => item.Name)</span><span>@Html.DisplayFor(modelItem => item.Description)</span>
            </div>
            <div>
                <span><a href="@Html.DisplayFor(modelItem => item.Url)">@Html.DisplayFor(modelItem => item.Url)</a></span>
            </div>
            <div style="margin-bottom: 25pt">
                <span style="margin-right: 5pt">Date added:</span><span style="margin-right: 5pt">@Html.DisplayFor(modelItem => item.DateAdded)</span>
                <span style="margin-right: 5pt">|</span><span style="margin-right: 5pt">Likes:</span>
                <span id="@("likes" + item.Id)" style="margin-right: 5pt">@Html.DisplayFor(modelItem => item.Likes)</span>
                @if (_signInManager.IsSignedIn(User))
                {
                    var loggedUserId = _userManager.GetUserId(User);
                    if (String.Equals(loggedUserId, item.UserId))
                    {
                        likeInputDisabled = "disabled";
                        likeInputValue = "Your link";
                    }
                    if (!String.Equals(loggedUserId, item.UserId) && _context.Likes.Any(l => l.UserId == loggedUserId && l.LinkId == item.Id))
                    {
                        likeInputDisabled = "disabled";
                        likeInputValue = "Liked";
                    }

                    <span style="margin-right: 5pt">|</span>
                    <input id="@("input" + item.Id)" type="button" value="@likeInputValue" onclick="Like(@item.Id, @item.Likes)" @likeInputDisabled />

                    likeInputDisabled = "";
                    likeInputValue = "Like";
                }
            </div>
        </li>
    }

</ol>

@{
    var prevDisabled = !Model.PreviousPageExists() ? "disabled" : "";
    var nextDisabled = !Model.NextPageExists() ? "disabled" : "";
}

<div>
    <a asp-action="Index" asp-route-pageNumber="@(Model.PageIndex - 1)" class="btn btn-default @prevDisabled">
        Previous page
    </a>
    <a asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 1)" class="btn btn-default @nextDisabled" style="float: right">
        Next page
    </a>
</div>

<script type="text/javascript">
    function Like(linkId, linkLikes) {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Like", "Links")',
            data: { id: linkId },
            dataType: 'json',
            success: function () {
                document.getElementById("input" + linkId).disabled = true;
                document.getElementById("input" + linkId).value = 'Liked';
                var addLike = linkLikes + 1;
                document.getElementById("likes" + linkId).innerHTML = addLike;
            }
        })
    }
</script>

AgregatorLinkow/Views/Links/UserLinks.cshtml
@model PaginatedList<AgregatorLinkow.Models.Link>;
@inject SignInManager<IdentityUser> _signInManager;

@{
    ViewData["Title"] = "UserLinks";
}

@if (!_signInManager.IsSignedIn(User))
{
    <div style="text-align: center; font-size: 20px">
        Login required.
    </div>
}
else
{
    <h1 class="text-center" style="margin-bottom: 20pt">Links added by @User.Identity.Name</h1>

    <ol start="@(1 + (Model.PageIndex - 1) * 100)">
        @foreach (var item in Model)
        {
            <li>
                <div>
                    <span style="margin-right: 25pt">@Html.DisplayFor(modelItem => item.Name)</span><span>@Html.DisplayFor(modelItem => item.Description)</span>
                </div>
                <div>
                    <span style="margin-right: 25pt"><a href="@Html.DisplayFor(modelItem => item.Url)">@Html.DisplayFor(modelItem => item.Url)</a></span>
                </div>
                <div style="margin-bottom: 25pt">
                    <span style="margin-right: 5pt">Date added:</span><span style="margin-right: 5pt">@Html.DisplayFor(modelItem => item.DateAdded)</span>
                    <span style="margin-right: 5pt">|</span><span style="margin-right: 5pt">Likes:</span><span style="margin-right: 5pt">@Html.DisplayFor(modelItem => item.Likes)</span>
                </div>
            </li>
        }

    </ol>

    var prevDisabled = !Model.PreviousPageExists() ? "disabled" : "";
    var nextDisabled = !Model.NextPageExists() ? "disabled" : "";


    <div style="margin-bottom: 20pt">
        <a asp-action="UserLinks" asp-controller="Links" asp-route-pageNumber="@(Model.PageIndex - 1)" class="btn btn-default @prevDisabled">
            Previous page
        </a>
        <a asp-action="UserLinks" asp-controller="Links" asp-route-pageNumber="@(Model.PageIndex + 1)" class="btn btn-default @nextDisabled" style="float: right">
            Next page
        </a>
    </div>

    <div style="text-align: center">
        <form asp-controller="Links" asp-action="Create" method="get">
            <button class="btn btn-dark" style="align-content: center">Add new link</button>
        </form>
    </div>
}